# Generated by Django 3.1 on 2020-08-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_topic', models.CharField(max_length=100)),
                ('set_date', models.DateField()),
                ('q1', models.CharField(max_length=200)),
                ('op_1a', models.CharField(max_length=100)),
                ('op_1b', models.CharField(max_length=100)),
                ('op_1c', models.CharField(max_length=100)),
                ('q1_ans', models.CharField(max_length=100)),
                ('q2', models.CharField(max_length=200)),
                ('op_2a', models.CharField(max_length=100)),
                ('op_2b', models.CharField(max_length=100)),
                ('op_2c', models.CharField(max_length=100)),
                ('q2_ans', models.CharField(max_length=100)),
                ('q3', models.CharField(max_length=200)),
                ('op_3a', models.CharField(max_length=100)),
                ('op_3b', models.CharField(max_length=100)),
                ('op_3c', models.CharField(max_length=100)),
                ('q3_ans', models.CharField(max_length=100)),
                ('q4', models.CharField(max_length=200)),
                ('op_4a', models.CharField(max_length=100)),
                ('op_4b', models.CharField(max_length=100)),
                ('op_4c', models.CharField(max_length=100)),
                ('q4_ans', models.CharField(max_length=100)),
                ('q5', models.CharField(max_length=200)),
                ('op_5a', models.CharField(max_length=100)),
                ('op_5b', models.CharField(max_length=100)),
                ('op_5c', models.CharField(max_length=100)),
                ('q5_ans', models.CharField(max_length=100)),
                ('set_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
        ),
    ]
